version: '3.8'

services:
  telegram_bot:
    image: ghcr.io/darkwood312/utils_tgbot:prod
    pull_policy: always
    container_name: tg_bot
#    volumes:
#      - ./cache:/app/cache
#      - ./logs:/app/logs
    restart: unless-stopped
    environment:
#      - TOKEN=
#      - SQL_HOST=
#      - SQL_PORT=
      - SQL_USER=bot
      - SQL_DATABASE=bot
      - SQL_PASSWORD=pass123
#      - DL_API_KEY=
#      - SHORTENER_API_URL=

  # Uncomment if you need a database
  # database:
  #   image: postgres:17
  #   container_name: postgres
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=pass123
  #     - POSTGRES_USER=bot
  #     - POSTGRES_DB=bot
  #   restart: always

# Uncomment if you need database volumes
# volumes:
#   postgres_data: